new commit

diff --git a/scripts/pre-commit/pre-commit b/scripts/pre-commit/pre-commit
--- a/scripts/pre-commit/pre-commit
+++ b/scripts/pre-commit/pre-commit
@@ -1,30 +1,30 @@
 #!/usr/bin/env bash
+#echo "
+#===============
+#|  Running detekt...
+#===============
+#"
+#./gradlew --no-daemon --stacktrace -PdisablePreDex detekt
+#
+#detektStatus=$?
+#
+## return 1 exit code if running checks fails
+#[ $detektStatus -ne 0 ] && exit 1
+
+#echo "
+#===================
+#|  Formatting code with ktlintFormat...
+#===================
+#"
+#./gradlew ktlintFormat
+
 echo "
-===============
-|  Running detekt...
-===============
-"
-./gradlew --no-daemon --stacktrace -PdisablePreDex detekt
-
-detektStatus=$?
-
-# return 1 exit code if running checks fails
-[ $detektStatus -ne 0 ] && exit 1
-
-echo "
 ===================
-|  Formatting code with ktlintFormat...
+|  Running Lint Check...
 ===================
 "
-./gradlew ktlintFormat
-
-echo "
-===================
-|  Running ktlintCheck...
-===================
-"
-
-./gradlew --no-daemon --stacktrace -PdisablePreDex ktlintCheck
+./gradlew lintDebug
+#./gradlew --no-daemon --stacktrace -PdisablePreDex ktlintCheck
 
 
 checkStyleStatus=$?
